[package]
name = "shorturl"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-files = "0.5.0"
actix-web = "3"
futures = "0.3"
url = "2.2.2"
blake3 = "0.3.7"

[dev-dependencies]
actix-rt = "2.2.0"
